# Generated by Django 4.2.21 on 2025-05-13 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aroma',
            fields=[
                ('id_aroma', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=32)),
                ('estado', models.IntegerField()),
            ],
            options={
                'db_table': 'aromas',
            },
        ),
    ]
