# Generated by Django 5.2 on 2025-10-23 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aromas', '0001_initial'),
        ('perfumes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aroma',
            new_name='Aromas',
        ),
    ]
