# Generated by Django 5.2 on 2025-10-23 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aromas', '0001_initial'),
        ('generos', '0001_initial'),
        ('marcas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfumes',
            fields=[
                ('id_perfume', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('tamanio', models.FloatField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=18)),
                ('imagen', models.ImageField(blank=True, upload_to='perfumes/')),
                ('estado', models.IntegerField()),
                ('id_aroma', models.ForeignKey(db_column='id_aroma', on_delete=django.db.models.deletion.CASCADE, to='aromas.aromas')),
                ('id_genero', models.ForeignKey(db_column='id_genero', on_delete=django.db.models.deletion.CASCADE, to='generos.generos')),
                ('id_marca', models.ForeignKey(db_column='id_marca', on_delete=django.db.models.deletion.CASCADE, to='marcas.marcas')),
            ],
            options={
                'db_table': 'perfumes',
            },
        ),
    ]
