# Generated by Django 5.2 on 2025-10-23 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Generos',
            fields=[
                ('id_genero', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=32)),
                ('estado', models.IntegerField()),
            ],
            options={
                'db_table': 'genero',
            },
        ),
    ]
